### PR TITLE
Cash Register

### PR DESCRIPTION
**Pull request by iamfarhatsharefi**
Summary
This pull request introduces a complete overhaul of the Cash Register application, improving functionality, design, and code quality. The primary enhancements include:

Functional Improvements:

Ensures accurate calculation of change due.
Adheres to FreeCodeCamp rules for cash register projects.
Enhanced error handling for invalid or insufficient cash inputs.
Design Enhancements:

Implements a vibrant and visually appealing design.
Adds a background image and CSS animations using @keyframes.
Ensures responsiveness with media queries for both mobile and desktop versions.
Code Quality Enhancements:

Refactors JavaScript code to follow best practices and latest ECMAScript standards.
Ensures the code passes ESLint checks for improved readability and maintainability.

### CODE REVIEW

**Comment by iamfarhatsharefi** [comment]
@Saqibi4213  @Nooria150 dear my partners please review my code.

**Comment by Saqibi4213** [comment]
> @Saqibi4213 @Nooria150 dear my partners please review my code.

**Hello**  @_iamfarhatsharefi_
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your design is responsive
_best  wishes!_

**Review by ahzamir — CHANGES_REQUESTED** [review]
Well done @iamfarhatsharefi 

- You have done a great job by implementing lots of requirements but still, your code misses some of the requirements:
- Your code on freecodecamp misses this one check:
  - When the price is less than the value in the #cash element, total cash in drawer cid is less than the change due, and the #purchase-btn element is clicked, the value in the #change-due element should be "Status: INSUFFICIENT_FUNDS".
- And as you can see in the [example](https://cash-register.freecodecamp.rocks/) you have to show everything for the user and I can see the results on your webpage.
image

**Comment by iamfarhatsharefi** [comment]
@ahzamir
first of all  i hope iam working correctely  according to your feedback because there wasnt any error or problem just working to show the result on webpage 
 and also one of your feedback was not passing the freecodecamp that actually it pass and i share the issue for you.

**Comment by ahzamir** [comment]
@iamfarhatsharefi 

- Still your project has the same issue, when user want to use your project how they should know how much is the price for the item how much they should pay. And same for the cashier how the cashier know how much change they should give to customer and which cash should they give.

- Check out the example below, you can see the price of the item, and the amount of cash user payed is 10 and then the result of change the cashier should give to the customer and n which cashes.

image

**Comment by ahzamir** [comment]
- Your design and project is like this and nothing is shown for the user or for the customer:

image

**Comment by iamfarhatsharefi** [comment]
@ahzamir i again try sir to do your feedback, please give me feedback.

**Review by ahzamir — APPROVED** [review]
### Hi @iamfarhatsharefi 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
